Repository FredTheDino/SMEK, pull requests merged in 2020-08, with the labels that each got.

#135 Add more documentation to math and assets
  src/asset/asset.h
  src/audio.h
  src/entity/entity.h
  src/math/smek_math.h
  src/math/smek_vec.h
  src/math/types.h
Labels: documentation

#138 Refactor the documentation
  docs/doc-builder.py
  docs/highlighter.py
  docs/style.css
Labels: documentation

#152 No pointer arith on void pointers
  src/entity/entity_types.cpp
  tools/entity_types_event.cpp
  tools/entity_types_event_callback.cpp
Labels: bug

#150 Add constraint concept to functions on vectors
  src/math/smek_quat.cpp
  src/math/smek_quat.h
  src/math/smek_vec.h
Labels: core

#140 Network heartbeat
  src/math/smek_quat.cpp
  src/math/smek_quat.h
  src/math/smek_vec.h
  src/network/network.cpp
  src/network/network.h
  src/network/package.cpp
  src/network/package.h
Labels: networking
